#!/usr/bin/env bash
#Displays the list of currently running processes
#Must show all processes, for all users, including those which might not have a TTY
#Display in a user-oriented format

ps -a -x -u -f
