#!/usr/bin/env bash
#A script that kills the process 7-highlander.

# Find the PID of the 7-highlander process
PID=$(pgrep -f "7-highlander")

# Check if the PID was found
if [ -n "$PID" ]; then
        kill -9 $PID
fi
