#!/usr/bin/env bash
# Using a while loop to display "Best School" 10 times

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]; then
		echo -e "Best School\nHi"
	else
		echo "Best School"
	fi
	
	((counter++))
done
