#!/usr/bin/env bash
# Using a while loop to iterate from 1 to 10

counter=1
while [ $counter -le 10 ]
do
	if [ $counter -eq 4 ]; then
		echo "bad Luck"
	elif [ $counter -eq 8 ]; then
		echo "good Luck"
	else
		echo "Best School"
	fi

	((counter++))
done
